/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib\thread-theme.ts
 * Command: astryx theme build lib\thread-theme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/**
 * thread-studio theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { threadStudioTheme } from './thread-studio';
 *   import './thread-studio.css';
 */
export const threadStudioTheme = {
  name: 'thread-studio',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#1D6B4C, #1D6B4C)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #003D18)",
    "--color-neutral": "light-dark(#151D191A, #DAE5DF33)",
    "--color-background-surface": "light-dark(#FFFFFF, #FFFFFF)",
    "--color-background-body": "light-dark(#FCFCFA, #FCFCFA)",
    "--color-overlay": "light-dark(#151D1966, #151D1999)",
    "--color-overlay-hover": "light-dark(#151D190D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#151D191A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#EEF0EA, #EEF0EA)",
    "--color-text-primary": "light-dark(#13201A, #13201A)",
    "--color-text-secondary": "light-dark(#59695F, #59695F)",
    "--color-text-disabled": "light-dark(#9AA79D, #9AA79D)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#000000, #F4FFF9)",
    "--color-icon-secondary": "light-dark(#26332C, #B9CAC1)",
    "--color-icon-disabled": "light-dark(#84948C, #53625A)",
    "--color-background-card": "light-dark(#FFFFFF, #FFFFFF)",
    "--color-background-popover": "light-dark(#FFFFFF, #FFFFFF)",
    "--color-background-inverted": "light-dark(#151D19, #F4FFF9)",
    "--color-border": "light-dark(#E2E6DD, #E2E6DD)",
    "--color-border-emphasized": "light-dark(#B7C2B0, #B7C2B0)",
    "--color-skeleton": "light-dark(#9EAFA6, #3B4A42)",
    "--color-track": "light-dark(#E5E8DF, #E5E8DF)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "0.9375rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.375rem",
    "--font-size-2xl": "1.625rem",
    "--font-size-3xl": "1.9375rem",
    "--font-size-4xl": "2.3125rem",
    "--font-size-5xl": "2.8125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.3846",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.4545",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.6",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.6",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.6",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.6",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2444",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2973",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.4194",
    "--radius-none": "0px",
    "--radius-inner": "13px",
    "--radius-element": "26px",
    "--radius-container": "39px",
    "--radius-page": "91px",
    "--radius-chat": "91px",
    "--radius-full": "9999px",
    "--duration-fast-min": "75ms",
    "--duration-fast": "110ms",
    "--duration-fast-max": "155ms",
    "--duration-medium-min": "155ms",
    "--duration-medium": "220ms",
    "--duration-medium-max": "315ms",
    "--duration-slow-min": "295ms",
    "--duration-slow": "420ms",
    "--duration-slow-max": "600ms",
    "--font-family-body": "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
    "--font-family-heading": "\"Space Grotesk\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
    "--font-family-code": "\"Geist Mono\", SFMono-Regular, ui-monospace, monospace"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "fontWeight": "var(--font-weight-semibold)",
        "transition": "transform var(--duration-fast) ease, filter var(--duration-fast) ease, box-shadow var(--duration-fast) ease",
        ":hover": {
          "filter": "contrast(1.05) brightness(1.02)",
          "transform": "translateY(-1px)"
        },
        ":active": {
          "transform": "translateY(0)"
        }
      },
      "variant:primary": {
        "backgroundImage": "linear-gradient(180deg, color-mix(in srgb, var(--color-accent) 100%, white 10%), var(--color-accent))",
        "boxShadow": "var(--shadow-low)",
        ":hover": {
          "boxShadow": "var(--shadow-med)",
          "transform": "translateY(-1px)"
        }
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "borderColor": "var(--color-border)",
        "boxShadow": "var(--shadow-low)"
      }
    },
    "badge": {
      "base": {
        "borderRadius": "var(--radius-full)"
      }
    },
    "side-nav": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)"
      }
    },
    "side-nav-heading": {
      "base": {
        "color": "var(--color-text-disabled)",
        "fontFamily": "var(--font-family-code)",
        "letterSpacing": "0.08em"
      }
    },
    "side-nav-item": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "padding": "var(--spacing-3) var(--spacing-4)",
        "transition": "background-color var(--duration-fast) ease, color var(--duration-fast) ease, box-shadow var(--duration-fast) ease",
        ":hover": {
          "backgroundColor": "var(--color-background-muted)"
        }
      },
      "selected": {
        "backgroundColor": "var(--color-accent-muted)",
        "color": "var(--color-text-accent)",
        "boxShadow": "inset 3px 0 0 var(--color-accent)",
        "fontWeight": "var(--font-weight-semibold)"
      }
    },
    "side-nav-section": {
      "base": {
        "marginBlockStart": "var(--spacing-6)"
      }
    },
    "selector": {
      "base": {
        "borderRadius": "var(--radius-element)"
      }
    },
    "top-nav": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
