/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib\thread-theme.ts
 * Command: astryx theme build lib\thread-theme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const threadStudioTheme: DefinedTheme;
