/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/thread-theme.ts
 * Command: astryx theme build lib/thread-theme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/**
 * thread-studio theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { threadStudioTheme } from './thread-studio';
 *   import './thread-studio.css';
 */
export const threadStudioTheme = {
  name: 'thread-studio',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#B12C1E, #FFB3A2)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #750000)",
    "--color-neutral": "light-dark(#2519161A, #F1DFDA33)",
    "--color-background-surface": "light-dark(#FBFAF6, #191816)",
    "--color-background-body": "light-dark(#F2EFE8, #11100E)",
    "--color-overlay": "light-dark(#25191666, #25191699)",
    "--color-overlay-hover": "light-dark(#2519160D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#2519161A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#EAE5DB, #27241F)",
    "--color-text-primary": "light-dark(#1B1916, #F6F2E9)",
    "--color-text-secondary": "light-dark(#666159, #B4ADA1)",
    "--color-text-disabled": "light-dark(#9C958A, #716A60)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#000000, #FFFBF9)",
    "--color-icon-secondary": "light-dark(#3F2C28, #DAC1BB)",
    "--color-icon-disabled": "light-dark(#A38C86, #6F5955)",
    "--color-background-card": "light-dark(#FBFAF6, #191816)",
    "--color-background-popover": "light-dark(#FFFFFF, #211F1C)",
    "--color-background-inverted": "light-dark(#251916, #FFFBF9)",
    "--color-border": "light-dark(#D9D2C6, #37332D)",
    "--color-border-emphasized": "light-dark(#9D9589, #6B645B)",
    "--color-skeleton": "light-dark(#BEA6A0, #56423E)",
    "--color-track": "light-dark(#DED7CB, #37332D)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.4375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "0.9375rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.3125rem",
    "--font-size-2xl": "1.5625rem",
    "--font-size-3xl": "1.8125rem",
    "--font-size-4xl": "2.125rem",
    "--font-size-5xl": "2.5rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.44",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.3333",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.6",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.6",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.6",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.6",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.3",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2941",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.3793",
    "--radius-none": "0px",
    "--radius-inner": "2px",
    "--radius-element": "5px",
    "--radius-container": "7px",
    "--radius-page": "17px",
    "--radius-chat": "17px",
    "--radius-full": "9999px",
    "--duration-fast-min": "65ms",
    "--duration-fast": "90ms",
    "--duration-fast-max": "125ms",
    "--duration-medium-min": "130ms",
    "--duration-medium": "180ms",
    "--duration-medium-max": "250ms",
    "--duration-slow-min": "260ms",
    "--duration-slow": "360ms",
    "--duration-slow-max": "500ms",
    "--font-family-body": "Geist, Inter, Avenir Next, -apple-system, BlinkMacSystemFont, system-ui, sans-serif",
    "--font-family-heading": "Geist, Inter, Avenir Next, -apple-system, BlinkMacSystemFont, system-ui, sans-serif",
    "--font-family-code": "\"Geist Mono\", SFMono-Regular, ui-monospace, monospace"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "fontWeight": "var(--font-weight-semibold)",
        ":hover": {
          "filter": "contrast(1.04)"
        }
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "borderColor": "var(--color-border-emphasized)",
        "boxShadow": "none"
      }
    },
    "side-nav": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)"
      }
    },
    "side-nav-item": {
      "base": {
        "borderRadius": "var(--radius-element)"
      },
      "selected": {
        "backgroundColor": "var(--color-accent-muted)",
        "color": "var(--color-text-accent)",
        "boxShadow": "inset calc(var(--border-width) * 2) 0 0 var(--color-accent)"
      }
    },
    "selector": {
      "base": {
        "borderRadius": "var(--radius-element)"
      }
    },
    "top-nav": {
      "base": {
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
